# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jj3Zi3j4Vk9ZsyKmoZbNbBpVWy-G3aO_
"""

from google.colab.patches import cv2_imshow
import cv2
rasm=cv2.imread("1rasm.jpeg.jpg")
cv2_imshow(rasm)

oqqora=cv2.cvtColor(rasm,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)

from google.colab.patches import cv2_imshow
import cv2
rasm=cv2.imread("3rasm.jpeg.jpg")
cv2_imshow(rasm)

oqqora=cv2.cvtColor(rasm,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)
import cv2

from  google.colab.patches import cv2_imshow
import cv2
rasm=cv2.imread("2rasm.jpeg.jpg")
cv2_imshow(rasm)

oqqora=cv2.cvtColor(rasm,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)
import cv2